---
- hosts: amazon_6
  remote_user: ec2-user
  become: yes

  tasks:
  - name: Atualizando o repo do zabbix
    yum: 
      name: https://repo.zabbix.com/zabbix/4.2/rhel/6/x86_64/zabbix-release-4.2-2.el6.noarch.rpm
      state: present  
   
  - name: Limpando o repo   
    shell: yum clean all
 
  - name: Backup do diretorio do Zabbix
    archive: 
      path: /etc/zabbix/ 
      dest: /root/zabbix.tar.gz 

  - name: Atualizacao do Zabbix agent 
    yum:  
      name: zabbix-agent
      state: latest
    notify: 
      - Restart Zabbix-agent

  handlers:
    - name: Restart Zabbix-agent
      service:
        name: zabbix-agent
        state: restarted
