---
- hosts: teste
  remote_user: ec2-user
  become: yes

  tasks:
  - name: Atualizando o repo do zabbix
    shell: rpm -Uvh https://repo.zabbix.com/zabbix/4.2/rhel/7/x86_64/zabbix-release-4.2-2.el7.noarch.rpm ;  yum clean all      
  
  - name: Backup do diretorio do Zabbix
    shell: tar czvf /root/zabbix.tar.gz /etc/zabbix/ 

  - name: Atualizacao do Zabbix agent 
    yum:  
     name: zabbix-agent
     state: latest

  - service:
     name: zabbix-agent
     state: started

  
